import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {createRequire} from 'node:module';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const require=createRequire(root+'/package.json'),katex=require('katex');
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const rich=s=>String(s).split(/(\$\$[\s\S]*?\$\$|\$[^$]+\$)/g).map(p=>{if(!p.startsWith('$'))return esc(p).replaceAll('\n','<br>');const display=p.startsWith('$$');return katex.renderToString(p.slice(display?2:1,display?-2:-1),{displayMode:display,throwOnError:true,output:'htmlAndMathml'});}).join('');
const pair=x=>`<div class="pair"><div class="en" lang="en">${rich(x.en)}</div><div class="cn" lang="zh">${rich(x.zh)}</div></div>`;
function validate(meta,script,ref){
 if(meta.publication!=='approved')throw Error('Lesson is not approved for public build');
 for(const k of ['id','courseId','termId','weekId','title','brand','date','sourceSummary','notice','closingIndex','durationMinutes'])if(meta[k]===undefined)throw Error('Missing lesson field '+k);
 for(const k of ['courseId','termId','weekId'])if(!/^[a-z0-9-]+$/.test(meta[k]))throw Error('Unsafe path '+k);
 if(!Array.isArray(script)||!Array.isArray(ref)||!ref.length||!(meta.closingIndex>0&&meta.closingIndex<script.length))throw Error('Invalid lesson structure');
 const ids=new Set();for(const e of ref){if(!/^[KABCT][0-9]+$/.test(e.id)||ids.has(e.id))throw Error('Invalid/duplicate ID '+e.id);ids.add(e.id);for(const k of ['title','scope','source','questionEn','questionZh'])if(!e[k])throw Error(e.id+' missing '+k);for(const k of ['overview','say'])if(!e[k]?.en||!e[k]?.zh)throw Error(e.id+' missing pair '+k);for(const k of ['prerequisites','strategy','steps','pitfalls'])if(!e[k]?.length||e[k].some(p=>!p.en||!p.zh))throw Error(e.id+' missing pair list '+k);}
 for(const [i,s] of script.entries()){if(!s.title||!s.subtitle||!s.quick?.say?.en||!s.quick?.say?.cn||!s.quick?.action||!s.quick?.check?.en||!s.quick?.check?.cn||!s.blocks?.length)throw Error('Incomplete section '+i);if(s.topic&&!ids.has(s.topic))throw Error('Missing topic '+s.topic);for(const b of s.blocks)if(!(['action','note','math'].includes(b.type)?b.text:b.en&&b.cn))throw Error('Incomplete script block');}
 const raw=JSON.stringify({meta,script,ref});if(/REPLACE_ME|<DEADLINE_VERIFY>|\/Users\/|one_hash=|f_hash=|github_pat_|ghp_[A-Za-z0-9]{30}/.test(raw))throw Error('Private path/token or unresolved placeholder');
}
function diagram(file){if(!/^diagrams\/[a-z0-9-]+\.svg$/.test(file))throw Error('Unsafe diagram path');return fs.readFileSync(path.join(root,file),'utf8');}
function sourceMap(meta){if(!meta.activitySources)return '';return `<details class="source-map"><summary>题目从哪里来？A1–A6 与正式 13 题的关系</summary><p><strong>A1–A6 来自另一份导师活动建议，不是正式题单的题号。</strong>下表最后一栏仅是知识联系，不是原题一一对应。</p><p>Question source: <em>Linear Algebra tutorial ideas 2026</em>, Week 1, pp. 2–3. A labels are local; links below show related ideas, not identical questions.</p><ol>${meta.activitySources.map(x=>`<li><strong>${esc(x.id)} · 导师文件第 ${x.page} 页</strong><p>${esc(x.original)}</p><p>${esc(x.relationship)} <a href="library.html#entry=${esc(x.related)}">查看相关正式题 →</a></p></li>`).join('')}</ol><p><strong>完整资料：</strong>12 项前提知识 K1–K12；6 项课堂活动 A1–A6；正式题单 Q1.1–Q1.13 共 13 题（C1 + B2–B13）；另有课程安排 T1。覆盖完整不等于一节全讲。</p><p><strong>来源边界：</strong>题意按课程材料整理，并非所有题目的逐字转录；详细讲法、图示与检查是备课补充。Q1.1 完整解答只用于教师备课，本周课堂只给起步提示。Exit check 与 (−2,0) 小变式是自编检查。</p><a href="https://www.ole.bris.ac.uk/ultra/courses/_270159_1/document/_10463117_1?view=content&amp;state=view" target="_blank" rel="noopener">学校正式 Problem Sheet 1（需学校登录）↗</a><p>${esc(meta.reviewLabel)}</p></details>`;}
function activitySource(meta,id){const x=meta.activitySources?.find(x=>x.id===id);return x?`<aside class="activity-source"><strong>原题：导师活动建议 p. ${x.page} · ${esc(x.original)}</strong><p>不是正式题单题号。知识联系：${esc(x.relationship)} <a href="library.html#entry=${esc(x.related)}" target="_blank" rel="noopener">相关正式题 ↗</a></p></aside>`:'';}
function boardGuide(g){if(!g)return '';if(!g.steps?.length||g.steps.some(x=>!x.en||!x.zh))throw Error('Incomplete board guide');return `<details class="board-guide"><summary>BOARD PLAN · 展开板书图与绘制顺序（含答案）</summary><p class="board-warning">先让学生尝试；此处供教师照画，不直接展示全解。</p><div class="board-image">${diagram(g.diagram)}</div><ol>${g.steps.map(x=>`<li>${pair(x)}</li>`).join('')}</ol></details>`;}
const labels={say:'SAY · 你说',answer:'ANSWER · 先听学生，再核对',backup:'BACKUP · 按需使用',student:'STUDENT · 学生可能问',read:'READ · 英文读法'};
const block=b=>b.type==='math'?`<div class="board"><div class="board-label">BOARD · 板书</div><div class="equation">${katex.renderToString(b.text,{displayMode:true,throwOnError:true,output:'htmlAndMathml'})}</div></div>`:['action','note'].includes(b.type)?`<aside class="${b.type}"><b>${b.type==='action'?'动作 · 不读出':'教师备注'}</b><div>${rich(b.text)}</div></aside>`:['backup','student'].includes(b.type)?`<details class="speech ${b.type}"><summary>${labels[b.type]}</summary><div class="en">${rich(b.en)}</div><div class="cn">${rich(b.cn)}</div></details>`:`<div class="speech ${b.type}"><div class="label">${labels[b.type]}</div><div class="en" lang="en">${rich(b.en)}</div><div class="cn" lang="zh">${rich(b.cn)}</div></div>`;
function build(dir){const meta=JSON.parse(fs.readFileSync(dir+'/lesson.json')),script=JSON.parse(fs.readFileSync(dir+'/script.json')),ref=JSON.parse(fs.readFileSync(dir+'/reference.json'));validate(meta,script,ref);const route=`courses/${meta.courseId}/${meta.termId}/${meta.weekId}`,out=root+'/'+route,prefix='../../../../';fs.mkdirSync(out,{recursive:true});
 const rendered=ref.map(e=>({id:e.id,title:e.title,scope:e.scope,search:JSON.stringify(e).toLowerCase(),html:`<article class="entry" id="${e.id}"><div class="eyebrow">${e.id} · ${esc(e.scope)}</div><h1>${esc(e.title)}</h1><p class="source">${esc(e.source)}</p><section class="overview"><h2>START HERE · 这项在讲什么？</h2>${pair(e.overview)}</section><section class="question"><h2>${e.id.startsWith('K')?'CONCEPT · 概念与前提':'QUESTION · 完整题目'}</h2>${pair({en:e.questionEn,zh:e.questionZh})}</section>${e.diagram?`<section class="diagram"><h2>SKETCH · 图像理解</h2>${diagram(e.diagram)}</section>`:''}<section class="prerequisites"><h2>BEFORE YOU START · 所需知识</h2>${e.prerequisites.map(pair).join('')}</section><section class="strategy"><h2>HOW TO THINK · 怎么想到？</h2>${e.strategy.map((p,i)=>`<div class="worked-strategy"><h3>Idea ${i+1} · 思路 ${i+1}</h3>${pair(p)}</div>`).join('')}</section><details class="solution" ${e.id==='C1'?'':'open'}><summary>${e.id==='C1'?'TUTOR ONLY · 教师完整解答；本周课堂不要展开':'WORKED ANSWER · 逐步详解'}</summary><ol class="worked-list">${e.steps.map((p,i)=>`<li class="worked"><span class="number">${i+1}</span>${pair(p)}</li>`).join('')}</ol></details>${e.alternatives?.length?`<section class="alternatives"><h2>OTHER APPROACHES · 其他方法与例子</h2>${e.alternatives.map(pair).join('')}</section>`:''}<section class="say"><h2>IN CLASS · 英文讲法</h2>${pair(e.say)}</section><section class="pitfalls"><h2>WATCH OUT · 易错点与边界</h2>${e.pitfalls.map(pair).join('')}</section></article>`}));
 fs.writeFileSync(out+'/library-data.json',JSON.stringify(rendered));
 const nav=script.map((s,i)=>`<button data-go="${i}" class="nav-item"><span class="step-no">${String(i).padStart(2,'0')}</span>${esc(s.title)}</button>`).join(''),options=script.map((s,i)=>`<option value="${i}">${i} ${esc(s.title)}</option>`).join('');
 const sections=script.map((s,i)=>{const e=ref.find(e=>e.id===s.topic);return `<section class="lesson" id="step-${i}" data-index="${i}" ${i===1?'':'hidden'}><div class="eyebrow">${i>=1&&i<=meta.closingIndex?'课堂主线':'随手查阅'} / ${i}</div><h1 tabindex="-1">${esc(s.title)}</h1><p class="timing">${esc(s.subtitle)}</p>${activitySource(meta,s.topic)}${e?`<a class="topic-reference" href="library.html#entry=${e.id}" target="_blank" rel="noopener">${e.id} 完整思路与详解 ↗</a><details class="question-panel"><summary>展开完整题目（不含答案）</summary><div class="en">${rich(e.questionEn)}</div><div class="cn">${rich(e.questionZh)}</div></details>`:''}<div class="quick-card"><h2>课堂速览 · 看提示，不必照读整页</h2><div class="quick-part"><h3>SAY · 你说</h3><div class="en">${rich(s.quick.say.en)}</div><div class="cn">${rich(s.quick.say.cn)}</div></div><div class="quick-action"><b>DO · 接下来做什么</b><p>${rich(s.quick.action)}</p></div><div class="quick-part"><h3>CHECK · 具体检查</h3><div class="en">${rich(s.quick.check.en)}</div><div class="cn">${rich(s.quick.check.cn)}</div></div></div>${boardGuide(s.boardGuide)}<div class="full-blocks">${s.blocks.map(block).join('')}</div></section>`;}).join('');
 const head=`<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#132c46"><link rel="icon" href="${prefix}icon.svg"><link rel="stylesheet" href="${prefix}vendor/katex/katex.min.css">`;
 fs.writeFileSync(out+'/index.html',`<!doctype html><html lang="zh-CN"><head>${head}<title>${esc(meta.title)} · 授课稿</title><link rel="stylesheet" href="${prefix}style.css?v=hub1"><link rel="stylesheet" href="${prefix}board.css?v=1"></head><body data-storage-key="${meta.id}-teaching" data-closing="${meta.closingIndex}" data-minutes="${meta.durationMinutes}" data-worker="${prefix}sw.js"><a class="skip-link" href="#main">跳到讲稿</a><header class="topbar"><div class="brand"><div><strong>${esc(meta.brand)}</strong><span>英文带课稿 · 中文备注</span></div></div><div class="toolbar"><button id="mode-toggle" aria-pressed="false">切换课堂速览</button><button id="cn-toggle" aria-pressed="true">中文对照 · 开</button><div class="font-tools"><button id="font-down" aria-label="缩小字号">A−</button><button id="font-up" aria-label="增大字号">A＋</button></div><span id="offline" role="status">正在准备离线</span></div></header><div class="workspace"><nav class="sidebar" aria-label="授课环节"><a class="library-link" href="${prefix}hub.html">全部课程与周次 →</a><a class="library-link" href="library.html">完整题目、答案与思路 →</a><p class="nav-title">LESSON FLOW</p>${nav}<div class="sidebar-note">${esc(meta.flow)}<br>${esc(meta.closingHint||"剩余 3 分钟收尾，准时结束。")}<br>资料完整，不等于全讲。</div></nav><main id="main"><a class="library-link mobile-library" href="${prefix}hub.html">全部课程与周次 →</a><a class="library-link mobile-library" href="library.html">完整题目、答案与思路 →</a><div class="mobile-nav"><label for="section-select">当前环节</label><select id="section-select">${options}</select></div>${meta.printPack?`<aside class="print-pack"><strong>PRINT · 课前打印</strong><a href="student-worksheet.pdf" target="_blank" rel="noopener">学生英文题纸 · 无答案 · 3页 A4 ↗</a><a href="tutor-board-guide.pdf" target="_blank" rel="noopener">教师板书参考 · 含答案 · 6页 A4 ↗</a><small>此处是普通 3 页题纸，不是邮件中的 6 页空白背页打印版。学生用题纸；教师板书参考含答案，请勿发给学生。</small></aside>`:''}${sourceMap(meta)}<div class="lesson-tools"><span id="mode-help">详细讲稿 · SAY 可说，动作与备注不读出</span><button id="finish-now">时间不够？直接收尾 →</button></div><div class="reading">${sections}</div></main></div><footer class="bottom"><div class="timer"><button id="timer-toggle">开始 ${meta.durationMinutes} 分钟</button><output id="clock">${meta.durationMinutes}:00</output><button id="timer-reset" aria-label="重置计时">重置</button></div><div class="pager"><button id="prev">← 上一环节</button><span id="position"></span><button id="next" class="primary">下一环节 →</button></div></footer><script src="${prefix}app.js?v=hub1"></script></body></html>`);
 const template=fs.readFileSync(root+'/library.html','utf8');let lib=template.replace('<title>Pure Week 1 · 完整备课资料</title>',`<title>${esc(meta.title)} · 完整备课资料</title>`).replace('<body>',`<body data-storage-key="${meta.id}-library" data-reference="./library-data.json" data-worker="${prefix}sw.js">`).replace('∈ PURE / WEEK 01',esc(meta.brand)).replaceAll('href="./"','href="index.html"').replace('href="hub.html"',`href="${prefix}hub.html"`).replaceAll('href="icon.svg"',`href="${prefix}icon.svg"`).replace('href="vendor/',`href="${prefix}vendor/`).replace('href="library.css?v=font1"',`href="${prefix}library.css?v=font1"`).replace('src="library.js?v=hub1"',`src="${prefix}library.js?v=hub1"`).replace(/<div class="notice">[\s\S]*?<\/div>/,`<div class="notice"><strong>${esc(meta.title)} · 教师备课资料</strong><p>${esc(meta.notice)}</p><p>${esc(meta.sourceSummary)}</p><span id="offline" role="status">正在加载资料</span></div>`).replace('>Part A</button>','>课堂活动</button>').replace('>Part B</button>','>题单 1.2–1.13</button>').replace('>Part C</button>','>待交题 1.1</button>').replace('>错误证明</button>','>课程安排</button>').replace('例如 A3、subset、量词','例如 B9、polar、三角不等式');if(meta.activitySources)lib=lib.replace('</head>',`<link rel="stylesheet" href="${prefix}board.css?v=1"></head>`).replace('<div id="load-status"',sourceMap(meta)+'<div id="load-status"');fs.writeFileSync(out+'/library.html',lib);
 const report={id:meta.id,route,referenceItems:ref.length,scriptSections:script.length,pairedWorkedSteps:ref.reduce((n,e)=>n+e.steps.length,0),closingIndex:meta.closingIndex,questionIds:ref.filter(e=>e.id.startsWith('B')||e.id==='C1').map(e=>e.id)};fs.writeFileSync(out+'/coverage.json',JSON.stringify(report,null,2));return report;
}
const selected=process.argv[2];const dirs=selected?[path.resolve(root,selected)]:fs.readdirSync(root+'/content',{recursive:true}).filter(f=>f.endsWith('lesson.json')).map(f=>path.dirname(root+'/content/'+f));for(const dir of dirs)console.log(JSON.stringify(build(dir)));
